### ISSUE TITLE
Profile vs Media-Type+File extension

### ISSUE THREAD

**Issue by HadrienGardeur** [HadrienGardeur/audiobook-manifest#1]
While the audiobook manifest is technically a profile of the EPUB BFF manifest, there's some value in having a dedicated media type and file extension for it:
- it is doubtful that audio players will support EPUB or comics, because of that we need a way for these apps to identify an audiobook or an audiobook manifest
- if we rely strictly on a media parameter to indicate that we're using a profile, it's doubtful that audio apps will be able to rely on it at all
- on the other hand, on pretty much every OS out there it is possible for an app to register itself for specific media types and/or file extensions

That said, purely from an API point of view, a generic media type is probably better as it could be universally understood.

Anyone has thoughts on this?

**Comment by leonardr** [comment]
I find the OS integration argument pretty convincing. It doesn't seem likely that apps can register themselves for specific profiles of media types.

I think we should also support profiles though. Profiles allow BFF EPUBs to contain weird multimedia things we didn't think of. But we should probably have media types for all-text books, all-audio books, and all-video books.

**Comment by HadrienGardeur** [comment]
There are now several extension points with:

- additional context documents
- different value for `@type`

I think this is good enough to cover profiles.
