### ISSUE TITLE
readBy, narrator, performer?

### ISSUE THREAD

**Issue by daryanypl** [HadrienGardeur/audiobook-manifest#10]
conversation so far:

[Darya] "readBy" should be "narrator".

[Hadrien] That's what I had initially, but I used "readBy" to align with schema.org. I'm fine with either of those two.

[Darya] Consistency within the document feels good, but if the local inconsistency in naming is for the sake of overall consistency somewhere else, I can understand.  There are many words that can go into the field: "read by", "narrator", "performance" (for when it's a radio play performed by a cast of actors, for example).  It can be a single person, or a "full cast".  On Audible, I listen to books that are collections of short stories, each chapter narrated by a different actor or actors.  In their interface, they don't list which actors do which chapters, they just list the array of actors.  At some point in the future, we might want to be able to do better.

**Comment by HadrienGardeur** [comment]
Currently, we're using `narrator` but it points to https://bib.schema.org/readBy

There's no mechanism to provide that information per track, it's only for the whole publication. This could be handled through a new collection role in the future, but it's a bit heavy handed.

**Comment by HadrienGardeur** [comment]
To provide this information per resource we could use https://schema.org/hasPart :

```json
"schema:hasPart": [
  {
    "schema:url": "chapter1.mp3",
    "narrator": "Jane Narrator"
  },
  {
    "schema:url": "chapter2.mp3",
    "narrator": "Michael Narrator"
  }
]
```

Since this is already covered by the extension mechanisms in the Readium Web Publication Manifest, I'm closing the issue.
