### ISSUE TITLE
Needs original text copyright and performance copyright information.

### ISSUE THREAD

**Issue by daryanypl** [HadrienGardeur/audiobook-manifest#11]
conversation so far:
[Hadrien] Copyright information can be expressed using schema.org info, just not sure how easily we can indicate the difference between original text and performance copyright info.

[Darya] This will be important for us to have, for example when a commercial publisher re-narrates an out-of-copyright classic.  In fact, we'll need to have several identifiable copyrights attached to the book listing:
- one for the book text
- one for the cover art
- one for the vocal performance
Depending on which copyrights are what, we'll then handle the book parts differently.

**Comment by HadrienGardeur** [comment]
I can't find a generic rights element in schema.org. There's a license element, but this is meant to be a URI.

It's also a little unclear how we could indicate that rights apply to specific elements. 
For the cover art, it's probably the easiest since the cover has its own link. For the original text or a specific performance, I don't really know how we could express that.

**Comment by HadrienGardeur** [comment]
After looking into this issue a bit more, I've found two elements that could fit the requirements in schema.org:

- https://schema.org/copyrightHolder
- https://schema.org/license

Using https://schema.org/hasPart, you could extend the `metadata` section of the manifest to include something like that:
```json
"schema:hasPart": [
  {
    "@type": "http://schema.org/VisualArtwork",
    "schema:url": "cover.jpg",
    "schema:license": "https://creativecommons.org/publicdomain/zero/1.0/"
  }
]
```

**Comment by HadrienGardeur** [comment]
This is IMO covered by the existing extension points in the Readium Web Publication Manifest, therefore I'm closing this issue.
