### ISSUE TITLE
Multiformat files and fallback chain

### ISSUE THREAD

**Issue by pettarin** [HadrienGardeur/audiobook-manifest#8]
Since it looks this is an attempt to cover a wide range of use cases, and especially for audio publications living on the Web, then there should be a mechanism to specify multiple formats for a given audio file. For example, the client might be able to play a given format (OGG) but not another (MP3), or the user might want a low-fi version (64kbps mono) to save bandwidth, rather than an hi-fi version (256kbps stereo), etc.

**Comment by HadrienGardeur** [comment]
Right now, this is supported at a publication level where you can provide `alternate` links to other publications. A client can then look at the format/bitrate indicated in the link and select the right one.

I have mixed feeling about supporting that at a track level, simply to avoid having something too complex, but from a technical perspective it can easily be done (provide `alternate` links per track).

**Comment by pettarin** [comment]
Good enough I think. Closing.
